
server:
  port: 9090

spring:
  cloud:
    config:
      server:
        git:
          uri:   https://github.com/pratikw1859/rent-car-local-config-server.git
          
  application:
    name: spring-cloud-config-server        